@Host = http://localhost:5128

###

GET {{Host}}/api/todos

###

POST {{Host}}/api/todos
Content-Type: application/json; charset=utf-8

{
    "id": 1,
    "title": "Test",
    "done": false
}

###

PATCH {{Host}}/api/todos/5/toggle

###

DELETE {{Host}}/api/todos/5

###